In [124]:
#here i load the libraries
import numpy as np
import pandas as pd
import sklearn as sk
import matplotlib
import matplotlib.pyplot as plt
from IPython.display import display
import seaborn as sns
import datetime
sns.set_theme()

In [125]:
January=pd.read_csv('January.csv')
January.drop('Unnamed: 0',axis=1,inplace=True)
January.info()
January

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5458998 entries, 0 to 5458997
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 333.2+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Haarlem Spaarnwoude,2016-01-01T00:10:00Z,PT0S
1,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Bad Nieuweschans,2016-01-01T00:10:00Z,PT0S
2,DVD,Duivendrecht,7495,Sprinter,NS,Duivendrecht,2016-01-01T00:11:00Z,PT0S
3,DDRS,Dordrecht Stadspolders,36795,Stoptrein,Arriva,Dordrecht Stadspolders,2016-01-01T00:11:00Z,PT0S
4,EMNZ,Emmen Zuid,8083,Stoptrein,Arriva,Emmen Zuid,2016-01-01T00:11:00Z,PT0S
...,...,...,...,...,...,...,...,...
5458993,DDRS,Dordrecht Stadspolders,36782,Stoptrein,Arriva,Dordrecht,2016-01-31T22:58:00Z,PT0S
5458994,HIL,Hillegom,6395,Sprinter,NS,Leiden Centraal,2016-01-31T23:00:00Z,PT0S
5458995,DT,Delft,5182,Sprinter,NS,Den Haag Centraal,2016-01-31T23:00:00Z,PT0S
5458996,VB,Voorburg,9893,Sprinter,NS,Utrecht Centraal,2016-01-31T23:01:00Z,PT0S
5458997,HWD,Heerhugowaard,3078,Intercity,NS,Den Helder,2016-01-31T23:00:38Z,PT2M38S

In [126]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
January['Train Planned Departure']=pd.to_datetime(January['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
January['Train Planned Departure1']=January['Train Planned Departure'].astype(str)
January[['DepartureDate','DepartureTime']]= January['Train Planned Departure1'].str.split(' ', expand = True)
January['DepartureDate']=pd.to_datetime(January['DepartureDate'])
January

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Haarlem Spaarnwoude,2016-01-01 00:10:00,PT0S,2016-01-01 00:10:00,2016-01-01,00:10:00
1,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Bad Nieuweschans,2016-01-01 00:10:00,PT0S,2016-01-01 00:10:00,2016-01-01,00:10:00
2,DVD,Duivendrecht,7495,Sprinter,NS,Duivendrecht,2016-01-01 00:11:00,PT0S,2016-01-01 00:11:00,2016-01-01,00:11:00
3,DDRS,Dordrecht Stadspolders,36795,Stoptrein,Arriva,Dordrecht Stadspolders,2016-01-01 00:11:00,PT0S,2016-01-01 00:11:00,2016-01-01,00:11:00
4,EMNZ,Emmen Zuid,8083,Stoptrein,Arriva,Emmen Zuid,2016-01-01 00:11:00,PT0S,2016-01-01 00:11:00,2016-01-01,00:11:00
...,...,...,...,...,...,...,...,...,...,...,...
5458993,DDRS,Dordrecht Stadspolders,36782,Stoptrein,Arriva,Dordrecht,2016-01-31 22:58:00,PT0S,2016-01-31 22:58:00,2016-01-31,22:58:00
5458994,HIL,Hillegom,6395,Sprinter,NS,Leiden Centraal,2016-01-31 23:00:00,PT0S,2016-01-31 23:00:00,2016-01-31,23:00:00
5458995,DT,Delft,5182,Sprinter,NS,Den Haag Centraal,2016-01-31 23:00:00,PT0S,2016-01-31 23:00:00,2016-01-31,23:00:00
5458996,VB,Voorburg,9893,Sprinter,NS,Utrecht Centraal,2016-01-31 23:01:00,PT0S,2016-01-31 23:01:00,2016-01-31,23:01:00
5458997,HWD,Heerhugowaard,3078,Intercity,NS,Den Helder,2016-01-31 23:00:38,PT2M38S,2016-01-31 23:00:38,2016-01-31,23:00:38

In [127]:
#then i make the depature time a time delta (Actually want to make it a normal time format)
January['DepartureTime']=pd.to_timedelta(January['DepartureTime'].str.strip())
print(January.info())
January

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5458998 entries, 0 to 5458997
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 458.1+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Haarlem Spaarnwoude,2016-01-01 00:10:00,PT0S,2016-01-01 00:10:00,2016-01-01,0 days 00:10:00
1,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Bad Nieuweschans,2016-01-01 00:10:00,PT0S,2016-01-01 00:10:00,2016-01-01,0 days 00:10:00
2,DVD,Duivendrecht,7495,Sprinter,NS,Duivendrecht,2016-01-01 00:11:00,PT0S,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
3,DDRS,Dordrecht Stadspolders,36795,Stoptrein,Arriva,Dordrecht Stadspolders,2016-01-01 00:11:00,PT0S,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
4,EMNZ,Emmen Zuid,8083,Stoptrein,Arriva,Emmen Zuid,2016-01-01 00:11:00,PT0S,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
...,...,...,...,...,...,...,...,...,...,...,...
5458993,DDRS,Dordrecht Stadspolders,36782,Stoptrein,Arriva,Dordrecht,2016-01-31 22:58:00,PT0S,2016-01-31 22:58:00,2016-01-31,0 days 22:58:00
5458994,HIL,Hillegom,6395,Sprinter,NS,Leiden Centraal,2016-01-31 23:00:00,PT0S,2016-01-31 23:00:00,2016-01-31,0 days 23:00:00
5458995,DT,Delft,5182,Sprinter,NS,Den Haag Centraal,2016-01-31 23:00:00,PT0S,2016-01-31 23:00:00,2016-01-31,0 days 23:00:00
5458996,VB,Voorburg,9893,Sprinter,NS,Utrecht Centraal,2016-01-31 23:01:00,PT0S,2016-01-31 23:01:00,2016-01-31,0 days 23:01:00
5458997,HWD,Heerhugowaard,3078,Intercity,NS,Den Helder,2016-01-31 23:00:38,PT2M38S,2016-01-31 23:00:38,2016-01-31,0 days 23:00:38

In [128]:
#Then i also put the delay in time delta format
January['Train Delay']=pd.to_timedelta(January['Train Delay'].str.strip())
January

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Haarlem Spaarnwoude,2016-01-01 00:10:00,0 days 00:00:00,2016-01-01 00:10:00,2016-01-01,0 days 00:10:00
1,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Bad Nieuweschans,2016-01-01 00:10:00,0 days 00:00:00,2016-01-01 00:10:00,2016-01-01,0 days 00:10:00
2,DVD,Duivendrecht,7495,Sprinter,NS,Duivendrecht,2016-01-01 00:11:00,0 days 00:00:00,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
3,DDRS,Dordrecht Stadspolders,36795,Stoptrein,Arriva,Dordrecht Stadspolders,2016-01-01 00:11:00,0 days 00:00:00,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
4,EMNZ,Emmen Zuid,8083,Stoptrein,Arriva,Emmen Zuid,2016-01-01 00:11:00,0 days 00:00:00,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
...,...,...,...,...,...,...,...,...,...,...,...
5458993,DDRS,Dordrecht Stadspolders,36782,Stoptrein,Arriva,Dordrecht,2016-01-31 22:58:00,0 days 00:00:00,2016-01-31 22:58:00,2016-01-31,0 days 22:58:00
5458994,HIL,Hillegom,6395,Sprinter,NS,Leiden Centraal,2016-01-31 23:00:00,0 days 00:00:00,2016-01-31 23:00:00,2016-01-31,0 days 23:00:00
5458995,DT,Delft,5182,Sprinter,NS,Den Haag Centraal,2016-01-31 23:00:00,0 days 00:00:00,2016-01-31 23:00:00,2016-01-31,0 days 23:00:00
5458996,VB,Voorburg,9893,Sprinter,NS,Utrecht Centraal,2016-01-31 23:01:00,0 days 00:00:00,2016-01-31 23:01:00,2016-01-31,0 days 23:01:00
5458997,HWD,Heerhugowaard,3078,Intercity,NS,Den Helder,2016-01-31 23:00:38,0 days 00:02:38,2016-01-31 23:00:38,2016-01-31,0 days 23:00:38

In [129]:
February=pd.read_csv('February.csv')
February.drop('Unnamed: 0',axis=1,inplace=True)
February.info()
February

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5248684 entries, 0 to 5248683
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 320.4+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-02-01T00:10:00Z,PT0S
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-02-01T00:10:00Z,PT0S
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-02-01T00:10:00Z,PT0S
3,HWD,Heerhugowaard,4082,Sprinter,NS,Den Helder,2016-02-01T00:10:00Z,PT0S
4,BGN,Bergen op Zoom,2674,Intercity,NS,Vlissingen,2016-01-31T23:01:00Z,PT0S
...,...,...,...,...,...,...,...,...
5248679,ASDM,Amsterdam Muiderpoort,5882,Sprinter,NS,Hoofddorp,2016-02-29T23:02:15Z,PT1M15S
5248680,ASA,Amsterdam Amstel,3082,Intercity,NS,Amsterdam Centraal,2016-02-29T23:00:16Z,PT1M16S
5248681,ZVT,Zandvoort aan Zee,5480,Sprinter,NS,Haarlem,2016-02-29T22:59:00Z,PT0S
5248682,PMO,Purmerend Overwhere,1591,Intercity,NS,Amsterdam Centraal,2016-02-29T23:01:00Z,PT0S
5248683,DMNZ,Diemen Zuid,4382,Sprinter,NS,Hoofddorp,2016-02-29T22:59:00Z,PT0S

In [130]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
February['Train Planned Departure']=pd.to_datetime(February['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
February['Train Planned Departure1']=February['Train Planned Departure'].astype(str)
February[['DepartureDate','DepartureTime']]= February['Train Planned Departure1'].str.split(' ', expand = True)
February['DepartureDate']=pd.to_datetime(February['DepartureDate'])
February
#then i make the depature time a time delta (Actually want to make it a normal time format)
February['DepartureTime']=pd.to_timedelta(February['DepartureTime'].str.strip())
print(February.info())
February
#Then i also put the delay in time delta format
February['Train Delay']=pd.to_timedelta(February['Train Delay'].str.strip())
February

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5248684 entries, 0 to 5248683
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 440.5+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-02-01 00:10:00,0 days 00:00:00,2016-02-01 00:10:00,2016-02-01,0 days 00:10:00
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-02-01 00:10:00,0 days 00:00:00,2016-02-01 00:10:00,2016-02-01,0 days 00:10:00
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-02-01 00:10:00,0 days 00:00:00,2016-02-01 00:10:00,2016-02-01,0 days 00:10:00
3,HWD,Heerhugowaard,4082,Sprinter,NS,Den Helder,2016-02-01 00:10:00,0 days 00:00:00,2016-02-01 00:10:00,2016-02-01,0 days 00:10:00
4,BGN,Bergen op Zoom,2674,Intercity,NS,Vlissingen,2016-01-31 23:01:00,0 days 00:00:00,2016-01-31 23:01:00,2016-01-31,0 days 23:01:00
...,...,...,...,...,...,...,...,...,...,...,...
5248679,ASDM,Amsterdam Muiderpoort,5882,Sprinter,NS,Hoofddorp,2016-02-29 23:02:15,0 days 00:01:15,2016-02-29 23:02:15,2016-02-29,0 days 23:02:15
5248680,ASA,Amsterdam Amstel,3082,Intercity,NS,Amsterdam Centraal,2016-02-29 23:00:16,0 days 00:01:16,2016-02-29 23:00:16,2016-02-29,0 days 23:00:16
5248681,ZVT,Zandvoort aan Zee,5480,Sprinter,NS,Haarlem,2016-02-29 22:59:00,0 days 00:00:00,2016-02-29 22:59:00,2016-02-29,0 days 22:59:00
5248682,PMO,Purmerend Overwhere,1591,Intercity,NS,Amsterdam Centraal,2016-02-29 23:01:00,0 days 00:00:00,2016-02-29 23:01:00,2016-02-29,0 days 23:01:00
5248683,DMNZ,Diemen Zuid,4382,Sprinter,NS,Hoofddorp,2016-02-29 22:59:00,0 days 00:00:00,2016-02-29 22:59:00,2016-02-29,0 days 22:59:00

In [131]:
March=pd.read_csv('March.csv')
March.drop('Unnamed: 0',axis=1,inplace=True)
March.info()
March

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5433078 entries, 0 to 5433077
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 331.6+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,LEDN,Leiden Centraal,2691,Intercity,NS,Amsterdam Centraal,2016-02-29T23:03:34Z,PT6M34S
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-03-01T00:10:00Z,PT0S
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-03-01T00:10:00Z,PT0S
3,CL,Culemborg,16084,Sprinter,NS,Utrecht Centraal,2016-02-29T22:59:00Z,PT0S
4,CAS,Castricum,14889,Sprinter,NS,Hoorn,2016-02-29T22:59:00Z,PT0S
...,...,...,...,...,...,...,...,...
5433073,ASSP,Amsterdam Science Park,5889,Sprinter,NS,Amersfoort,2016-03-31T22:00:36Z,PT36S
5433074,WP,Weesp,4684,Sprinter,NS,Amsterdam Centraal,2016-03-31T22:03:00Z,PT0S
5433075,ZP,Zutphen,3691,Intercity,NS,Arnhem,2016-03-31T21:59:30Z,PT1M30S
5433076,GDG,Gouda Goverwelle,9882,Sprinter,NS,Den Haag Centraal,2016-03-31T22:04:00Z,PT0S
5433077,DB,Driebergen-Zeist,3087,Intercity,NS,Nijmegen,2016-03-31T22:01:00Z,PT0S

In [132]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
March['Train Planned Departure']=pd.to_datetime(March['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
March['Train Planned Departure1']=March['Train Planned Departure'].astype(str)
March[['DepartureDate','DepartureTime']]= March['Train Planned Departure1'].str.split(' ', expand = True)
March['DepartureDate']=pd.to_datetime(March['DepartureDate'])
March
#then i make the depature time a time delta (Actually want to make it a normal time format)
March['DepartureTime']=pd.to_timedelta(March['DepartureTime'].str.strip())
print(March.info())
March
#Then i also put the delay in time delta format
March['Train Delay']=pd.to_timedelta(March['Train Delay'].str.strip())
March

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5433078 entries, 0 to 5433077
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 456.0+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,LEDN,Leiden Centraal,2691,Intercity,NS,Amsterdam Centraal,2016-02-29 23:03:34,0 days 00:06:34,2016-02-29 23:03:34,2016-02-29,0 days 23:03:34
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-03-01 00:10:00,0 days 00:00:00,2016-03-01 00:10:00,2016-03-01,0 days 00:10:00
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-03-01 00:10:00,0 days 00:00:00,2016-03-01 00:10:00,2016-03-01,0 days 00:10:00
3,CL,Culemborg,16084,Sprinter,NS,Utrecht Centraal,2016-02-29 22:59:00,0 days 00:00:00,2016-02-29 22:59:00,2016-02-29,0 days 22:59:00
4,CAS,Castricum,14889,Sprinter,NS,Hoorn,2016-02-29 22:59:00,0 days 00:00:00,2016-02-29 22:59:00,2016-02-29,0 days 22:59:00
...,...,...,...,...,...,...,...,...,...,...,...
5433073,ASSP,Amsterdam Science Park,5889,Sprinter,NS,Amersfoort,2016-03-31 22:00:36,0 days 00:00:36,2016-03-31 22:00:36,2016-03-31,0 days 22:00:36
5433074,WP,Weesp,4684,Sprinter,NS,Amsterdam Centraal,2016-03-31 22:03:00,0 days 00:00:00,2016-03-31 22:03:00,2016-03-31,0 days 22:03:00
5433075,ZP,Zutphen,3691,Intercity,NS,Arnhem,2016-03-31 21:59:30,0 days 00:01:30,2016-03-31 21:59:30,2016-03-31,0 days 21:59:30
5433076,GDG,Gouda Goverwelle,9882,Sprinter,NS,Den Haag Centraal,2016-03-31 22:04:00,0 days 00:00:00,2016-03-31 22:04:00,2016-03-31,0 days 22:04:00
5433077,DB,Driebergen-Zeist,3087,Intercity,NS,Nijmegen,2016-03-31 22:01:00,0 days 00:00:00,2016-03-31 22:01:00,2016-03-31,0 days 22:01:00

In [133]:
April=pd.read_csv('April.csv')
April.drop('Unnamed: 0',axis=1,inplace=True)
April.info()
April

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5511575 entries, 0 to 5511574
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 336.4+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,UTO,Utrecht Overvecht,5786,Sprinter,NS,Weesp,2016-03-31T22:08:42Z,PT9M42S
1,HOR,Hollandsche Rading,5786,Sprinter,NS,Weesp,2016-03-31T22:15:10Z,PT9M10S
2,HVSP,Hilversum Sportpark,5786,Sprinter,NS,Weesp,2016-03-31T22:19:46Z,PT8M46S
3,HVS,Hilversum,5786,Sprinter,NS,Hoofddorp,2016-03-31T22:23:32Z,PT8M32S
4,NDB,Naarden-Bussum,5786,Sprinter,NS,Hoofddorp,2016-03-31T22:31:52Z,PT7M52S
...,...,...,...,...,...,...,...,...
5511570,ASN,Assen,781,Intercity,NS,Groningen,2016-04-30T22:08:09Z,PT6M9S
5511571,GERP,Groningen Europapark,781,Intercity,NS,Groningen,2016-04-30T22:25:40Z,PT4M40S
5511572,HRN,Haren,781,Intercity,NS,Groningen,2016-04-30T22:20:08Z,PT5M8S
5511573,BL,Beilen,781,Intercity,NS,Groningen,2016-04-30T21:59:05Z,PT6M5S
5511574,ALMB,Almere Buiten,4384,Sprinter,NS,Hoofddorp,2016-04-30T21:58:00Z,PT0S

In [134]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
April['Train Planned Departure']=pd.to_datetime(April['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
April['Train Planned Departure1']=April['Train Planned Departure'].astype(str)
April[['DepartureDate','DepartureTime']]= April['Train Planned Departure1'].str.split(' ', expand = True)
April['DepartureDate']=pd.to_datetime(April['DepartureDate'])
April
#then i make the depature time a time delta (Actually want to make it a normal time format)
April['DepartureTime']=pd.to_timedelta(April['DepartureTime'].str.strip())
print(April.info())
April
#Then i also put the delay in time delta format
April['Train Delay']=pd.to_timedelta(April['Train Delay'].str.strip())
April

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5511575 entries, 0 to 5511574
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 462.5+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,UTO,Utrecht Overvecht,5786,Sprinter,NS,Weesp,2016-03-31 22:08:42,0 days 00:09:42,2016-03-31 22:08:42,2016-03-31,0 days 22:08:42
1,HOR,Hollandsche Rading,5786,Sprinter,NS,Weesp,2016-03-31 22:15:10,0 days 00:09:10,2016-03-31 22:15:10,2016-03-31,0 days 22:15:10
2,HVSP,Hilversum Sportpark,5786,Sprinter,NS,Weesp,2016-03-31 22:19:46,0 days 00:08:46,2016-03-31 22:19:46,2016-03-31,0 days 22:19:46
3,HVS,Hilversum,5786,Sprinter,NS,Hoofddorp,2016-03-31 22:23:32,0 days 00:08:32,2016-03-31 22:23:32,2016-03-31,0 days 22:23:32
4,NDB,Naarden-Bussum,5786,Sprinter,NS,Hoofddorp,2016-03-31 22:31:52,0 days 00:07:52,2016-03-31 22:31:52,2016-03-31,0 days 22:31:52
...,...,...,...,...,...,...,...,...,...,...,...
5511570,ASN,Assen,781,Intercity,NS,Groningen,2016-04-30 22:08:09,0 days 00:06:09,2016-04-30 22:08:09,2016-04-30,0 days 22:08:09
5511571,GERP,Groningen Europapark,781,Intercity,NS,Groningen,2016-04-30 22:25:40,0 days 00:04:40,2016-04-30 22:25:40,2016-04-30,0 days 22:25:40
5511572,HRN,Haren,781,Intercity,NS,Groningen,2016-04-30 22:20:08,0 days 00:05:08,2016-04-30 22:20:08,2016-04-30,0 days 22:20:08
5511573,BL,Beilen,781,Intercity,NS,Groningen,2016-04-30 21:59:05,0 days 00:06:05,2016-04-30 21:59:05,2016-04-30,0 days 21:59:05
5511574,ALMB,Almere Buiten,4384,Sprinter,NS,Hoofddorp,2016-04-30 21:58:00,0 days 00:00:00,2016-04-30 21:58:00,2016-04-30,0 days 21:58:00

In [135]:
May=pd.read_csv('May.csv')
May.drop('Unnamed: 0',axis=1,inplace=True)
May.info()
May

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5718506 entries, 0 to 5718505
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 349.0+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,WZ,Wezep,5688,Sprinter,NS,Utrecht Centraal,2016-04-30T21:58:00Z,PT0S
1,UTO,Utrecht Overvecht,5786,Sprinter,NS,Weesp,2016-04-30T22:00:00Z,PT1M
2,WH,Wijhe,3680,Intercity,NS,Zwolle,2016-04-30T22:00:00Z,PT0S
3,UTO,Utrecht Overvecht,5786,Sprinter,NS,Weesp,2016-04-30T22:00:00Z,PT1M
4,GERP,Groningen Europapark,9196,Sprinter,NS,Assen,2016-04-30T23:10:00Z,PT0S
...,...,...,...,...,...,...,...,...
5718501,HAD,Heemstede-Aerdenhout,2180,Intercity,NS,Amsterdam Centraal,2016-05-31T22:12:08Z,PT1M8S
5718502,OT,Oisterwijk,5288,Sprinter,NS,Tilburg Universiteit,2016-05-31T21:59:28Z,PT2M28S
5718503,HWZB,Halfweg-Zwanenburg,5478,Sprinter,NS,Amsterdam Centraal,2016-05-31T22:00:54Z,PT1M54S
5718504,ASS,Amsterdam Sloterdijk,5478,Sprinter,NS,Amsterdam Centraal,2016-05-31T22:05:30Z,PT1M30S
5718505,BRD,Barendrecht,15184,Sprinter,NS,Den Haag Centraal,2016-05-31T22:01:00Z,PT0S

In [136]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
May['Train Planned Departure']=pd.to_datetime(May['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
May['Train Planned Departure1']=May['Train Planned Departure'].astype(str)
May[['DepartureDate','DepartureTime']]= May['Train Planned Departure1'].str.split(' ', expand = True)
May['DepartureDate']=pd.to_datetime(May['DepartureDate'])
May
#then i make the depature time a time delta (Actually want to make it a normal time format)
May['DepartureTime']=pd.to_timedelta(May['DepartureTime'].str.strip())
print(May.info())
May
#Then i also put the delay in time delta format
May['Train Delay']=pd.to_timedelta(May['Train Delay'].str.strip())
May

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5718506 entries, 0 to 5718505
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 479.9+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,WZ,Wezep,5688,Sprinter,NS,Utrecht Centraal,2016-04-30 21:58:00,0 days 00:00:00,2016-04-30 21:58:00,2016-04-30,0 days 21:58:00
1,UTO,Utrecht Overvecht,5786,Sprinter,NS,Weesp,2016-04-30 22:00:00,0 days 00:01:00,2016-04-30 22:00:00,2016-04-30,0 days 22:00:00
2,WH,Wijhe,3680,Intercity,NS,Zwolle,2016-04-30 22:00:00,0 days 00:00:00,2016-04-30 22:00:00,2016-04-30,0 days 22:00:00
3,UTO,Utrecht Overvecht,5786,Sprinter,NS,Weesp,2016-04-30 22:00:00,0 days 00:01:00,2016-04-30 22:00:00,2016-04-30,0 days 22:00:00
4,GERP,Groningen Europapark,9196,Sprinter,NS,Assen,2016-04-30 23:10:00,0 days 00:00:00,2016-04-30 23:10:00,2016-04-30,0 days 23:10:00
...,...,...,...,...,...,...,...,...,...,...,...
5718501,HAD,Heemstede-Aerdenhout,2180,Intercity,NS,Amsterdam Centraal,2016-05-31 22:12:08,0 days 00:01:08,2016-05-31 22:12:08,2016-05-31,0 days 22:12:08
5718502,OT,Oisterwijk,5288,Sprinter,NS,Tilburg Universiteit,2016-05-31 21:59:28,0 days 00:02:28,2016-05-31 21:59:28,2016-05-31,0 days 21:59:28
5718503,HWZB,Halfweg-Zwanenburg,5478,Sprinter,NS,Amsterdam Centraal,2016-05-31 22:00:54,0 days 00:01:54,2016-05-31 22:00:54,2016-05-31,0 days 22:00:54
5718504,ASS,Amsterdam Sloterdijk,5478,Sprinter,NS,Amsterdam Centraal,2016-05-31 22:05:30,0 days 00:01:30,2016-05-31 22:05:30,2016-05-31,0 days 22:05:30
5718505,BRD,Barendrecht,15184,Sprinter,NS,Den Haag Centraal,2016-05-31 22:01:00,0 days 00:00:00,2016-05-31 22:01:00,2016-05-31,0 days 22:01:00

In [137]:
June=pd.read_csv('June.csv')
June.drop('Unnamed: 0',axis=1,inplace=True)
June.info()
June

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5743211 entries, 0 to 5743210
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 350.5+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,UTO,Utrecht Overvecht,5786,Sprinter,NS,Hilversum,2016-05-31T22:00:00Z,PT1M
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-05-31T23:10:00Z,PT0S
2,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-05-31T23:10:00Z,PT0S
3,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-05-31T23:10:00Z,PT0S
4,BD,Breda,1987,Intercity,NS,Venlo,2016-05-31T22:10:17Z,PT19M17S
...,...,...,...,...,...,...,...,...
5743206,ASD,Amsterdam Centraal,1584,Intercity,NS,Hoorn,2016-06-30T22:09:00Z,PT0S
5743207,BET,Best,9687,Sprinter,NS,Deurne,2016-06-30T22:00:55Z,PT2M55S
5743208,HM,Helmond,9688,Sprinter,NS,'s-Hertogenbosch,2016-06-30T21:59:00Z,PT0S
5743209,EDC,Ede Centrum,31374,Stoptrein,Valleilijn,Amersfoort,2016-06-30T21:59:00Z,PT0S
5743210,BSMZ,Bussum Zuid,5887,Sprinter,NS,Amersfoort,2016-06-30T22:00:09Z,PT6M9S

In [138]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
June['Train Planned Departure']=pd.to_datetime(June['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
June['Train Planned Departure1']=June['Train Planned Departure'].astype(str)
June[['DepartureDate','DepartureTime']]= June['Train Planned Departure1'].str.split(' ', expand = True)
June['DepartureDate']=pd.to_datetime(June['DepartureDate'])
June
#then i make the depature time a time delta (Actually want to make it a normal time format)
June['DepartureTime']=pd.to_timedelta(June['DepartureTime'].str.strip())
print(June.info())
June
#Then i also put the delay in time delta format
June['Train Delay']=pd.to_timedelta(June['Train Delay'].str.strip())
June

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5743211 entries, 0 to 5743210
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 482.0+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,UTO,Utrecht Overvecht,5786,Sprinter,NS,Hilversum,2016-05-31 22:00:00,0 days 00:01:00,2016-05-31 22:00:00,2016-05-31,0 days 22:00:00
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-05-31 23:10:00,0 days 00:00:00,2016-05-31 23:10:00,2016-05-31,0 days 23:10:00
2,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-05-31 23:10:00,0 days 00:00:00,2016-05-31 23:10:00,2016-05-31,0 days 23:10:00
3,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-05-31 23:10:00,0 days 00:00:00,2016-05-31 23:10:00,2016-05-31,0 days 23:10:00
4,BD,Breda,1987,Intercity,NS,Venlo,2016-05-31 22:10:17,0 days 00:19:17,2016-05-31 22:10:17,2016-05-31,0 days 22:10:17
...,...,...,...,...,...,...,...,...,...,...,...
5743206,ASD,Amsterdam Centraal,1584,Intercity,NS,Hoorn,2016-06-30 22:09:00,0 days 00:00:00,2016-06-30 22:09:00,2016-06-30,0 days 22:09:00
5743207,BET,Best,9687,Sprinter,NS,Deurne,2016-06-30 22:00:55,0 days 00:02:55,2016-06-30 22:00:55,2016-06-30,0 days 22:00:55
5743208,HM,Helmond,9688,Sprinter,NS,'s-Hertogenbosch,2016-06-30 21:59:00,0 days 00:00:00,2016-06-30 21:59:00,2016-06-30,0 days 21:59:00
5743209,EDC,Ede Centrum,31374,Stoptrein,Valleilijn,Amersfoort,2016-06-30 21:59:00,0 days 00:00:00,2016-06-30 21:59:00,2016-06-30,0 days 21:59:00
5743210,BSMZ,Bussum Zuid,5887,Sprinter,NS,Amersfoort,2016-06-30 22:00:09,0 days 00:06:09,2016-06-30 22:00:09,2016-06-30,0 days 22:00:09

In [139]:
July=pd.read_csv('July.csv')
July.drop('Unnamed: 0',axis=1,inplace=True)
July.info()
July

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5683049 entries, 0 to 5683048
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 346.9+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,ASSP,Amsterdam Science Park,5882,Sprinter,NS,Hoofddorp,2016-06-30T21:59:16Z,PT1M16S
1,SDM,Schiedam Centrum,4191,Sprinter,NS,Rotterdam Centraal,2016-06-30T22:02:50Z,PT10M50S
2,NWL,Schiedam Nieuwland,4191,Sprinter,NS,Rotterdam Centraal,2016-06-30T21:59:59Z,PT10M59S
3,HIL,Hillegom,6395,Sprinter,NS,Leiden Centraal,2016-06-30T22:01:23Z,PT1M23S
4,NWL,Schiedam Nieuwland,4191,Sprinter,NS,Rotterdam Centraal,2016-06-30T21:59:59Z,PT10M59S
...,...,...,...,...,...,...,...,...
5683044,ODB,Oudenbosch,5186,Sprinter,NS,Den Haag Centraal,2016-07-31T21:59:54Z,PT1M54S
5683045,ZLW,Lage Zwaluwe,5186,Sprinter,NS,Den Haag Centraal,2016-07-31T22:11:03Z,PT1M3S
5683046,ZDK,Zaandam Kogerveld,3384,Sprinter,NS,Hoorn Kersenboogerd,2016-07-31T22:01:00Z,PT0S
5683047,BRD,Barendrecht,15184,Sprinter,NS,Den Haag Centraal,2016-07-31T22:01:00Z,PT0S
5683048,ODB,Oudenbosch,5186,Sprinter,NS,Den Haag Centraal,2016-07-31T21:59:54Z,PT1M54S

In [140]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
July['Train Planned Departure']=pd.to_datetime(July['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
July['Train Planned Departure1']=July['Train Planned Departure'].astype(str)
July[['DepartureDate','DepartureTime']]= July['Train Planned Departure1'].str.split(' ', expand = True)
July['DepartureDate']=pd.to_datetime(July['DepartureDate'])
July
#then i make the depature time a time delta (Actually want to make it a normal time format)
July['DepartureTime']=pd.to_timedelta(July['DepartureTime'].str.strip())
print(July.info())
July
#Then i also put the delay in time delta format
July['Train Delay']=pd.to_timedelta(July['Train Delay'].str.strip())
July

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5683049 entries, 0 to 5683048
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 476.9+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,ASSP,Amsterdam Science Park,5882,Sprinter,NS,Hoofddorp,2016-06-30 21:59:16,0 days 00:01:16,2016-06-30 21:59:16,2016-06-30,0 days 21:59:16
1,SDM,Schiedam Centrum,4191,Sprinter,NS,Rotterdam Centraal,2016-06-30 22:02:50,0 days 00:10:50,2016-06-30 22:02:50,2016-06-30,0 days 22:02:50
2,NWL,Schiedam Nieuwland,4191,Sprinter,NS,Rotterdam Centraal,2016-06-30 21:59:59,0 days 00:10:59,2016-06-30 21:59:59,2016-06-30,0 days 21:59:59
3,HIL,Hillegom,6395,Sprinter,NS,Leiden Centraal,2016-06-30 22:01:23,0 days 00:01:23,2016-06-30 22:01:23,2016-06-30,0 days 22:01:23
4,NWL,Schiedam Nieuwland,4191,Sprinter,NS,Rotterdam Centraal,2016-06-30 21:59:59,0 days 00:10:59,2016-06-30 21:59:59,2016-06-30,0 days 21:59:59
...,...,...,...,...,...,...,...,...,...,...,...
5683044,ODB,Oudenbosch,5186,Sprinter,NS,Den Haag Centraal,2016-07-31 21:59:54,0 days 00:01:54,2016-07-31 21:59:54,2016-07-31,0 days 21:59:54
5683045,ZLW,Lage Zwaluwe,5186,Sprinter,NS,Den Haag Centraal,2016-07-31 22:11:03,0 days 00:01:03,2016-07-31 22:11:03,2016-07-31,0 days 22:11:03
5683046,ZDK,Zaandam Kogerveld,3384,Sprinter,NS,Hoorn Kersenboogerd,2016-07-31 22:01:00,0 days 00:00:00,2016-07-31 22:01:00,2016-07-31,0 days 22:01:00
5683047,BRD,Barendrecht,15184,Sprinter,NS,Den Haag Centraal,2016-07-31 22:01:00,0 days 00:00:00,2016-07-31 22:01:00,2016-07-31,0 days 22:01:00
5683048,ODB,Oudenbosch,5186,Sprinter,NS,Den Haag Centraal,2016-07-31 21:59:54,0 days 00:01:54,2016-07-31 21:59:54,2016-07-31,0 days 21:59:54

In [141]:
August=pd.read_csv('August.csv')
August.drop('Unnamed: 0',axis=1,inplace=True)
August.info()
August

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5692769 entries, 0 to 5692768
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 347.5+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-07-31T23:10:00Z,PT0S
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-07-31T23:10:00Z,PT0S
2,HWD,Heerhugowaard,4082,Sprinter,NS,Den Helder,2016-07-31T23:10:00Z,PT0S
3,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-07-31T23:10:00Z,PT0S
4,SDM,Schiedam Centrum,15195,Sprinter,NS,Dordrecht,2016-07-31T23:10:00Z,PT0S
...,...,...,...,...,...,...,...,...
5692764,ASD,Amsterdam Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31T22:03:00Z,PT5M
5692765,ASS,Amsterdam Sloterdijk,12682,Intercity,NS,Rotterdam Centraal,2016-08-31T22:08:34Z,PT4M34S
5692766,ASDL,Amsterdam Lelylaan,12682,Intercity,NS,Rotterdam Centraal,2016-08-31T22:12:16Z,PT4M16S
5692767,SHL,Schiphol Airport,12682,Intercity,NS,Rotterdam Centraal,2016-08-31T22:19:43Z,PT3M43S
5692768,LEDN,Leiden Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31T22:36:28Z,PT1M28S

In [142]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
August['Train Planned Departure']=pd.to_datetime(August['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
August['Train Planned Departure1']=August['Train Planned Departure'].astype(str)
August[['DepartureDate','DepartureTime']]= August['Train Planned Departure1'].str.split(' ', expand = True)
August['DepartureDate']=pd.to_datetime(August['DepartureDate'])
August

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,23:10:00
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,23:10:00
2,HWD,Heerhugowaard,4082,Sprinter,NS,Den Helder,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,23:10:00
3,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,23:10:00
4,SDM,Schiedam Centrum,15195,Sprinter,NS,Dordrecht,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,23:10:00
...,...,...,...,...,...,...,...,...,...,...,...
5692764,ASD,Amsterdam Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:03:00,PT5M,2016-08-31 22:03:00,2016-08-31,22:03:00
5692765,ASS,Amsterdam Sloterdijk,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:08:34,PT4M34S,2016-08-31 22:08:34,2016-08-31,22:08:34
5692766,ASDL,Amsterdam Lelylaan,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:12:16,PT4M16S,2016-08-31 22:12:16,2016-08-31,22:12:16
5692767,SHL,Schiphol Airport,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:19:43,PT3M43S,2016-08-31 22:19:43,2016-08-31,22:19:43
5692768,LEDN,Leiden Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:36:28,PT1M28S,2016-08-31 22:36:28,2016-08-31,22:36:28

In [143]:
#then i make the depature time a time delta (Actually want to make it a normal time format)
August['DepartureTime']=pd.to_timedelta(August['DepartureTime'].str.strip())
print(August.info())
August

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5692769 entries, 0 to 5692768
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 477.8+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
2,HWD,Heerhugowaard,4082,Sprinter,NS,Den Helder,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
3,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
4,SDM,Schiedam Centrum,15195,Sprinter,NS,Dordrecht,2016-07-31 23:10:00,PT0S,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
...,...,...,...,...,...,...,...,...,...,...,...
5692764,ASD,Amsterdam Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:03:00,PT5M,2016-08-31 22:03:00,2016-08-31,0 days 22:03:00
5692765,ASS,Amsterdam Sloterdijk,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:08:34,PT4M34S,2016-08-31 22:08:34,2016-08-31,0 days 22:08:34
5692766,ASDL,Amsterdam Lelylaan,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:12:16,PT4M16S,2016-08-31 22:12:16,2016-08-31,0 days 22:12:16
5692767,SHL,Schiphol Airport,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:19:43,PT3M43S,2016-08-31 22:19:43,2016-08-31,0 days 22:19:43
5692768,LEDN,Leiden Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:36:28,PT1M28S,2016-08-31 22:36:28,2016-08-31,0 days 22:36:28

In [144]:
#Then i also put the delay in time delta format
August['Train Delay']=pd.to_timedelta(August['Train Delay'].str.strip())
August

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-07-31 23:10:00,0 days 00:00:00,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
1,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-07-31 23:10:00,0 days 00:00:00,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
2,HWD,Heerhugowaard,4082,Sprinter,NS,Den Helder,2016-07-31 23:10:00,0 days 00:00:00,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
3,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-07-31 23:10:00,0 days 00:00:00,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
4,SDM,Schiedam Centrum,15195,Sprinter,NS,Dordrecht,2016-07-31 23:10:00,0 days 00:00:00,2016-07-31 23:10:00,2016-07-31,0 days 23:10:00
...,...,...,...,...,...,...,...,...,...,...,...
5692764,ASD,Amsterdam Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:03:00,0 days 00:05:00,2016-08-31 22:03:00,2016-08-31,0 days 22:03:00
5692765,ASS,Amsterdam Sloterdijk,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:08:34,0 days 00:04:34,2016-08-31 22:08:34,2016-08-31,0 days 22:08:34
5692766,ASDL,Amsterdam Lelylaan,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:12:16,0 days 00:04:16,2016-08-31 22:12:16,2016-08-31,0 days 22:12:16
5692767,SHL,Schiphol Airport,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:19:43,0 days 00:03:43,2016-08-31 22:19:43,2016-08-31,0 days 22:19:43
5692768,LEDN,Leiden Centraal,12682,Intercity,NS,Rotterdam Centraal,2016-08-31 22:36:28,0 days 00:01:28,2016-08-31 22:36:28,2016-08-31,0 days 22:36:28

In [145]:
September=pd.read_csv('September.csv')
September.drop('Unnamed: 0',axis=1,inplace=True)
September.info()
September

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5697591 entries, 0 to 5697590
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 347.8+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-08-31T23:10:00Z,PT0S
1,BV,Beverwijk,14895,Sprinter,NS,Alkmaar,2016-08-31T23:10:00Z,PT0S
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-08-31T23:10:00Z,PT0S
3,ZVT,Zandvoort aan Zee,5480,Sprinter,NS,Haarlem,2016-08-31T21:59:00Z,PT0S
4,HWZB,Halfweg-Zwanenburg,5478,Sprinter,NS,Amsterdam Centraal,2016-08-31T21:59:00Z,PT0S
...,...,...,...,...,...,...,...,...
5697586,ALMB,Almere Buiten,4387,Sprinter,NS,Almere Oostvaarders,2016-09-30T22:01:00Z,PT0S
5697587,O,Oss,3686,Intercity,NS,Arnhem Centraal,2016-09-30T22:01:31Z,PT5M31S
5697588,KPNZ,Kampen Zuid,4688,Sprinter,NS,Lelystad Centrum,2016-09-30T22:06:25Z,PT1M25S
5697589,CVM,Chevremont,32088,Stoptrein,Veolia,Maastricht,2016-09-30T22:01:00Z,PT0S
5697590,KRD,Kerkrade Centrum,32088,Stoptrein,Veolia,Maastricht,2016-09-30T21:59:00Z,PT0S

In [146]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
September['Train Planned Departure']=pd.to_datetime(September['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
September['Train Planned Departure1']=September['Train Planned Departure'].astype(str)
September[['DepartureDate','DepartureTime']]= September['Train Planned Departure1'].str.split(' ', expand = True)
September['DepartureDate']=pd.to_datetime(September['DepartureDate'])
September
#then i make the depature time a time delta (Actually want to make it a normal time format)
September['DepartureTime']=pd.to_timedelta(September['DepartureTime'].str.strip())
print(September.info())
September
#Then i also put the delay in time delta format
September['Train Delay']=pd.to_timedelta(September['Train Delay'].str.strip())
September

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5697591 entries, 0 to 5697590
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 478.2+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-08-31 23:10:00,0 days 00:00:00,2016-08-31 23:10:00,2016-08-31,0 days 23:10:00
1,BV,Beverwijk,14895,Sprinter,NS,Alkmaar,2016-08-31 23:10:00,0 days 00:00:00,2016-08-31 23:10:00,2016-08-31,0 days 23:10:00
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-08-31 23:10:00,0 days 00:00:00,2016-08-31 23:10:00,2016-08-31,0 days 23:10:00
3,ZVT,Zandvoort aan Zee,5480,Sprinter,NS,Haarlem,2016-08-31 21:59:00,0 days 00:00:00,2016-08-31 21:59:00,2016-08-31,0 days 21:59:00
4,HWZB,Halfweg-Zwanenburg,5478,Sprinter,NS,Amsterdam Centraal,2016-08-31 21:59:00,0 days 00:00:00,2016-08-31 21:59:00,2016-08-31,0 days 21:59:00
...,...,...,...,...,...,...,...,...,...,...,...
5697586,ALMB,Almere Buiten,4387,Sprinter,NS,Almere Oostvaarders,2016-09-30 22:01:00,0 days 00:00:00,2016-09-30 22:01:00,2016-09-30,0 days 22:01:00
5697587,O,Oss,3686,Intercity,NS,Arnhem Centraal,2016-09-30 22:01:31,0 days 00:05:31,2016-09-30 22:01:31,2016-09-30,0 days 22:01:31
5697588,KPNZ,Kampen Zuid,4688,Sprinter,NS,Lelystad Centrum,2016-09-30 22:06:25,0 days 00:01:25,2016-09-30 22:06:25,2016-09-30,0 days 22:06:25
5697589,CVM,Chevremont,32088,Stoptrein,Veolia,Maastricht,2016-09-30 22:01:00,0 days 00:00:00,2016-09-30 22:01:00,2016-09-30,0 days 22:01:00
5697590,KRD,Kerkrade Centrum,32088,Stoptrein,Veolia,Maastricht,2016-09-30 21:59:00,0 days 00:00:00,2016-09-30 21:59:00,2016-09-30,0 days 21:59:00

In [147]:
October=pd.read_csv('October.csv')
October.drop('Unnamed: 0',axis=1,inplace=True)
October.info()
October

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5805596 entries, 0 to 5805595
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 354.3+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,BV,Beverwijk,14895,Sprinter,NS,Alkmaar,2016-09-30T23:10:00Z,PT0S
1,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-09-30T23:10:00Z,PT0S
2,GERP,Groningen Europapark,9196,Sprinter,NS,Assen,2016-09-30T23:10:00Z,PT0S
3,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-09-30T23:10:00Z,PT0S
4,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-09-30T23:10:00Z,PT0S
...,...,...,...,...,...,...,...,...
5805591,GS,Goes,2672,Intercity,NS,Vlissingen,2016-10-31T23:02:00Z,PT0S
5805592,LLS,Lelystad Centrum,4685,Sprinter,NS,Zwolle,2016-10-31T23:05:00Z,PT0S
5805593,GS,Goes,2672,Intercity,NS,Vlissingen,2016-10-31T23:02:00Z,PT0S
5805594,OT,Oisterwijk,5288,Sprinter,NS,Tilburg Universiteit,2016-10-31T22:59:41Z,PT1M41S
5805595,AH,Arnhem Centraal,3085,Intercity,NS,Nijmegen,2016-10-31T23:04:00Z,PT0S

In [148]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
October['Train Planned Departure']=pd.to_datetime(October['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
October['Train Planned Departure1']=October['Train Planned Departure'].astype(str)
October[['DepartureDate','DepartureTime']]= October['Train Planned Departure1'].str.split(' ', expand = True)
October['DepartureDate']=pd.to_datetime(October['DepartureDate'])
October
#then i make the depature time a time delta (Actually want to make it a normal time format)
October['DepartureTime']=pd.to_timedelta(October['DepartureTime'].str.strip())
print(October.info())
October
#Then i also put the delay in time delta format
October['Train Delay']=pd.to_timedelta(October['Train Delay'].str.strip())
October

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5805596 entries, 0 to 5805595
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 487.2+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,BV,Beverwijk,14895,Sprinter,NS,Alkmaar,2016-09-30 23:10:00,0 days 00:00:00,2016-09-30 23:10:00,2016-09-30,0 days 23:10:00
1,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-09-30 23:10:00,0 days 00:00:00,2016-09-30 23:10:00,2016-09-30,0 days 23:10:00
2,GERP,Groningen Europapark,9196,Sprinter,NS,Assen,2016-09-30 23:10:00,0 days 00:00:00,2016-09-30 23:10:00,2016-09-30,0 days 23:10:00
3,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-09-30 23:10:00,0 days 00:00:00,2016-09-30 23:10:00,2016-09-30,0 days 23:10:00
4,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-09-30 23:10:00,0 days 00:00:00,2016-09-30 23:10:00,2016-09-30,0 days 23:10:00
...,...,...,...,...,...,...,...,...,...,...,...
5805591,GS,Goes,2672,Intercity,NS,Vlissingen,2016-10-31 23:02:00,0 days 00:00:00,2016-10-31 23:02:00,2016-10-31,0 days 23:02:00
5805592,LLS,Lelystad Centrum,4685,Sprinter,NS,Zwolle,2016-10-31 23:05:00,0 days 00:00:00,2016-10-31 23:05:00,2016-10-31,0 days 23:05:00
5805593,GS,Goes,2672,Intercity,NS,Vlissingen,2016-10-31 23:02:00,0 days 00:00:00,2016-10-31 23:02:00,2016-10-31,0 days 23:02:00
5805594,OT,Oisterwijk,5288,Sprinter,NS,Tilburg Universiteit,2016-10-31 22:59:41,0 days 00:01:41,2016-10-31 22:59:41,2016-10-31,0 days 22:59:41
5805595,AH,Arnhem Centraal,3085,Intercity,NS,Nijmegen,2016-10-31 23:04:00,0 days 00:00:00,2016-10-31 23:04:00,2016-10-31,0 days 23:04:00

In [149]:
November=pd.read_csv('November.csv')
November.drop('Unnamed: 0',axis=1,inplace=True)
November.info()
November

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6252976 entries, 0 to 6252975
Data columns (total 8 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Station Code             object
 1   Station Name             object
 2   Train Number             int64
 3   Train Type               object
 4   Train Company            object
 5   Train Destination        object
 6   Train Planned Departure  object
 7   Train Delay              object
dtypes: int64(1), object(7)
memory usage: 381.7+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-11-01T00:10:00Z,PT0S
1,SDM,Schiedam Centrum,15195,Sprinter,NS,Dordrecht,2016-11-01T00:10:00Z,PT0S
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-11-01T00:10:00Z,PT0S
3,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-11-01T00:10:00Z,PT0S
4,GDM,Geldermalsen,6086,Sprinter,NS,Utrecht Centraal,2016-10-31T23:07:00Z,PT0S
...,...,...,...,...,...,...,...,...
6252971,WL,Wehl,30988,Stoptrein,Arriva,Arnhem Centraal,2016-11-30T23:01:11Z,PT11S
6252972,DVNK,De Vink,5791,Sprinter,NS,Diemen Zuid,2016-11-30T23:01:00Z,PT0S
6252973,DVD,Duivendrecht,4082,Sprinter,NS,Den Helder,2016-11-30T22:59:38Z,PT38S
6252974,ASDM,Amsterdam Muiderpoort,4082,Sprinter,NS,Den Helder,2016-11-30T23:06:05Z,PT5S
6252975,ASA,Amsterdam Amstel,4082,Sprinter,NS,Den Helder,2016-11-30T23:03:19Z,PT19S

In [150]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
November['Train Planned Departure']=pd.to_datetime(November['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
November['Train Planned Departure1']=November['Train Planned Departure'].astype(str)
November[['DepartureDate','DepartureTime']]= November['Train Planned Departure1'].str.split(' ', expand = True)
November['DepartureDate']=pd.to_datetime(November['DepartureDate'])
November
#then i make the depature time a time delta (Actually want to make it a normal time format)
November['DepartureTime']=pd.to_timedelta(November['DepartureTime'].str.strip())
print(November.info())
November
#Then i also put the delay in time delta format
November['Train Delay']=pd.to_timedelta(November['Train Delay'].str.strip())
November

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6252976 entries, 0 to 6252975
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               object
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 524.8+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,VDW,Vlaardingen West,4197,Sprinter,NS,Rotterdam Centraal,2016-11-01 00:10:00,0 days 00:00:00,2016-11-01 00:10:00,2016-11-01,0 days 00:10:00
1,SDM,Schiedam Centrum,15195,Sprinter,NS,Dordrecht,2016-11-01 00:10:00,0 days 00:00:00,2016-11-01 00:10:00,2016-11-01,0 days 00:10:00
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-11-01 00:10:00,0 days 00:00:00,2016-11-01 00:10:00,2016-11-01,0 days 00:10:00
3,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-11-01 00:10:00,0 days 00:00:00,2016-11-01 00:10:00,2016-11-01,0 days 00:10:00
4,GDM,Geldermalsen,6086,Sprinter,NS,Utrecht Centraal,2016-10-31 23:07:00,0 days 00:00:00,2016-10-31 23:07:00,2016-10-31,0 days 23:07:00
...,...,...,...,...,...,...,...,...,...,...,...
6252971,WL,Wehl,30988,Stoptrein,Arriva,Arnhem Centraal,2016-11-30 23:01:11,0 days 00:00:11,2016-11-30 23:01:11,2016-11-30,0 days 23:01:11
6252972,DVNK,De Vink,5791,Sprinter,NS,Diemen Zuid,2016-11-30 23:01:00,0 days 00:00:00,2016-11-30 23:01:00,2016-11-30,0 days 23:01:00
6252973,DVD,Duivendrecht,4082,Sprinter,NS,Den Helder,2016-11-30 22:59:38,0 days 00:00:38,2016-11-30 22:59:38,2016-11-30,0 days 22:59:38
6252974,ASDM,Amsterdam Muiderpoort,4082,Sprinter,NS,Den Helder,2016-11-30 23:06:05,0 days 00:00:05,2016-11-30 23:06:05,2016-11-30,0 days 23:06:05
6252975,ASA,Amsterdam Amstel,4082,Sprinter,NS,Den Helder,2016-11-30 23:03:19,0 days 00:00:19,2016-11-30 23:03:19,2016-11-30,0 days 23:03:19

In [151]:
December=pd.read_csv('December.csv')
December.drop('Unnamed: 0',axis=1,inplace=True)
December.info()
December

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1225410 entries, 0 to 1225409
Data columns (total 8 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   Station Code             1223493 non-null  object
 1   Station Name             1225410 non-null  object
 2   Train Number             1225410 non-null  int64
 3   Train Type               1225410 non-null  object
 4   Train Company            1225410 non-null  object
 5   Train Destination        1225410 non-null  object
 6   Train Planned Departure  1225410 non-null  object
 7   Train Delay              1225410 non-null  object
dtypes: int64(1), object(7)
memory usage: 74.8+ MB

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-12-01T00:10:00Z,PT0S
1,BV,Beverwijk,14895,Sprinter,NS,Alkmaar,2016-12-01T00:10:00Z,PT0S
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-12-01T00:10:00Z,PT0S
3,DVD,Duivendrecht,4082,Sprinter,NS,Den Helder,2016-11-30T22:59:38Z,PT38S
4,ASDM,Amsterdam Muiderpoort,5889,Sprinter,NS,Amersfoort,2016-11-30T23:00:02Z,PT2M2S
...,...,...,...,...,...,...,...,...
1225405,ASD,Amsterdam Centraal,1406,Intercity,NS,Utrecht Centraal,2016-12-07T01:17:00Z,PT0S
1225406,DT,Delft,1410,Intercity,NS,Utrecht Centraal,2016-12-07T01:14:00Z,PT0S
1225407,GV,Den Haag HS,1414,Intercity,NS,Utrecht Centraal,2016-12-07T02:23:00Z,PT0S
1225408,LEDN,Leiden Centraal,1409,Intercity,NS,Rotterdam Centraal,2016-12-07T02:24:00Z,PT0S
1225409,DT,Delft,1410,Intercity,NS,Utrecht Centraal,2016-12-07T01:14:00Z,PT0S

In [152]:
#First I make a date from the date planned departure, then i make it a string in a new column fo i can split it into 2 columns 
#and make the date alone a date
December['Train Planned Departure']=pd.to_datetime(December['Train Planned Departure'], format="%Y-%m-%dT%H:%M:%SZ")
December['Train Planned Departure1']=December['Train Planned Departure'].astype(str)
December[['DepartureDate','DepartureTime']]= December['Train Planned Departure1'].str.split(' ', expand = True)
December['DepartureDate']=pd.to_datetime(December['DepartureDate'])
December
#then i make the depature time a time delta (Actually want to make it a normal time format)
December['DepartureTime']=pd.to_timedelta(December['DepartureTime'].str.strip())
print(December.info())
December
#Then i also put the delay in time delta format
December['Train Delay']=pd.to_timedelta(December['Train Delay'].str.strip())
December

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1225410 entries, 0 to 1225409
Data columns (total 11 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   Station Code              1223493 non-null  object
 1   Station Name              1225410 non-null  object
 2   Train Number              1225410 non-null  int64
 3   Train Type                1225410 non-null  object
 4   Train Company             1225410 non-null  object
 5   Train Destination         1225410 non-null  object
 6   Train Planned Departure   1225410 non-null  datetime64[ns]
 7   Train Delay               1225410 non-null  object
 8   Train Planned Departure1  1225410 non-null  object
 9   DepartureDate             1225410 non-null  datetime64[ns]
 10  DepartureTime             1225410 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(7), timedelta64[ns](1)
memory usage: 102.8+ MB
None

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Amsterdam Centraal,2016-12-01 00:10:00,0 days 00:00:00,2016-12-01 00:10:00,2016-12-01,0 days 00:10:00
1,BV,Beverwijk,14895,Sprinter,NS,Alkmaar,2016-12-01 00:10:00,0 days 00:00:00,2016-12-01 00:10:00,2016-12-01,0 days 00:10:00
2,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Groningen,2016-12-01 00:10:00,0 days 00:00:00,2016-12-01 00:10:00,2016-12-01,0 days 00:10:00
3,DVD,Duivendrecht,4082,Sprinter,NS,Den Helder,2016-11-30 22:59:38,0 days 00:00:38,2016-11-30 22:59:38,2016-11-30,0 days 22:59:38
4,ASDM,Amsterdam Muiderpoort,5889,Sprinter,NS,Amersfoort,2016-11-30 23:00:02,0 days 00:02:02,2016-11-30 23:00:02,2016-11-30,0 days 23:00:02
...,...,...,...,...,...,...,...,...,...,...,...
1225405,ASD,Amsterdam Centraal,1406,Intercity,NS,Utrecht Centraal,2016-12-07 01:17:00,0 days 00:00:00,2016-12-07 01:17:00,2016-12-07,0 days 01:17:00
1225406,DT,Delft,1410,Intercity,NS,Utrecht Centraal,2016-12-07 01:14:00,0 days 00:00:00,2016-12-07 01:14:00,2016-12-07,0 days 01:14:00
1225407,GV,Den Haag HS,1414,Intercity,NS,Utrecht Centraal,2016-12-07 02:23:00,0 days 00:00:00,2016-12-07 02:23:00,2016-12-07,0 days 02:23:00
1225408,LEDN,Leiden Centraal,1409,Intercity,NS,Rotterdam Centraal,2016-12-07 02:24:00,0 days 00:00:00,2016-12-07 02:24:00,2016-12-07,0 days 02:24:00
1225409,DT,Delft,1410,Intercity,NS,Utrecht Centraal,2016-12-07 01:14:00,0 days 00:00:00,2016-12-07 01:14:00,2016-12-07,0 days 01:14:00

In [153]:
TrainData=pd.concat([January, February, March, April, May, June, July, August, September, October, November, December])
TrainData.index = range(63471443)
TrainData

,Station Code,Station Name,Train Number,Train Type,Train Company,Train Destination,Train Planned Departure,Train Delay,Train Planned Departure1,DepartureDate,DepartureTime
0,HLMS,Haarlem Spaarnwoude,14882,Sprinter,NS,Haarlem Spaarnwoude,2016-01-01 00:10:00,0 days,2016-01-01 00:10:00,2016-01-01,0 days 00:10:00
1,NSCH,Bad Nieuweschans,37598,Stoptrein,Arriva,Bad Nieuweschans,2016-01-01 00:10:00,0 days,2016-01-01 00:10:00,2016-01-01,0 days 00:10:00
2,DVD,Duivendrecht,7495,Sprinter,NS,Duivendrecht,2016-01-01 00:11:00,0 days,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
3,DDRS,Dordrecht Stadspolders,36795,Stoptrein,Arriva,Dordrecht Stadspolders,2016-01-01 00:11:00,0 days,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
4,EMNZ,Emmen Zuid,8083,Stoptrein,Arriva,Emmen Zuid,2016-01-01 00:11:00,0 days,2016-01-01 00:11:00,2016-01-01,0 days 00:11:00
...,...,...,...,...,...,...,...,...,...,...,...
63471438,ASD,Amsterdam Centraal,1406,Intercity,NS,Utrecht Centraal,2016-12-07 01:17:00,0 days,2016-12-07 01:17:00,2016-12-07,0 days 01:17:00
63471439,DT,Delft,1410,Intercity,NS,Utrecht Centraal,2016-12-07 01:14:00,0 days,2016-12-07 01:14:00,2016-12-07,0 days 01:14:00
63471440,GV,Den Haag HS,1414,Intercity,NS,Utrecht Centraal,2016-12-07 02:23:00,0 days,2016-12-07 02:23:00,2016-12-07,0 days 02:23:00
63471441,LEDN,Leiden Centraal,1409,Intercity,NS,Rotterdam Centraal,2016-12-07 02:24:00,0 days,2016-12-07 02:24:00,2016-12-07,0 days 02:24:00
63471442,DT,Delft,1410,Intercity,NS,Utrecht Centraal,2016-12-07 01:14:00,0 days,2016-12-07 01:14:00,2016-12-07,0 days 01:14:00

In [154]:
TrainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63471443 entries, 0 to 63471442
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Station Code              object
 1   Station Name              object
 2   Train Number              int64
 3   Train Type                object
 4   Train Company             object
 5   Train Destination         object
 6   Train Planned Departure   datetime64[ns]
 7   Train Delay               timedelta64[ns]
 8   Train Planned Departure1  object
 9   DepartureDate             datetime64[ns]
 10  DepartureTime             timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(6), timedelta64[ns](2)
memory usage: 5.2+ GB